### ISSUE TITLE
Trying to include resource 

### ISSUE THREAD

**Issue by andy36** [katharsis-project/katharsis-core#277]
I have a user with a one to many relationship (for example: cars)
A car has a @JsonApiToOne relationship on it (for example: manufacturer)
I'm making the call user/{id}/cars and I want to include the manufacturer information in the include block using the include query param. Can I do that? How can I do that?

**Comment by meshuga** [comment]
In `findOne` method of user repository the created object should have initialized a list of cars and for each car there should be associated list of manufacturers. Then for requests like `user/{id}/cars?include[user]=cars.manufacturer` you should be able to get included manufacturers.

**Comment by d80harri** [comment]
Hi folks, Hope you don't mind if I high-jack this thread as I am (probably) facing the same problem. 

I have two resources (Flow and FlowItem) and a repository for each of them. A flow has a @JsonApiToMany relationship to a list of FlowItems. A flowItem on the other hand has a @JsonApiToOne relationship to its Flow. 

GET /flows?include[flow]=items works as expected. It returns all flows and each item for each flow in the included section of the response.

However the other way around does not work:

GET /flow.items?include[flow.items]=flow only returns all flow items but without the related flows. 

I implemented relationship repositories for Flow2FlowItem and FlowItem2Flow. All methods in FlowItem2Flow just throws a RuntimeException but is never called. However, I guess the relationship repository should not be necessary as my business logic always joins the flow to a flow.item, right?

As to meshugas comment above: Shouldn't it be GET user/{id}/cars?include[cars]=manufacturer? 

And one more question: What is the difference between JsonApiIncludeByDefault, JsonApiLookupIncludeAutomatically and @JsonApiToMany(lazy = false)

**Comment by meshuga** [comment]
Does your FlowItem repository `@FindAll` method return a reference to a flow along with the items?

`@JsonApiIncludeByDefault` annotation makes relationship resources to be included  in `include` section, `@JsonApiLookupIncludeAutomatically` allows Katharsis to fill in relationships using relationship repositories and `@JsonApiToMany(lazy = false)` enforce Katharsis not to include relationship information in `relationships.rel_name.data` field (it's useful in cases where there are many relations, like hundreds of them).

Yes, it should be `user/{id}/cars?include[cars]=manufacturer` :smile:

**Comment by d80harri** [comment]
> Does your FlowItem repository @FindAll method return a reference to a flow along with the items?

Yep it does:

```java
	@Override
	public D findOne(String id, QueryParams queryParams) {
		T resultEntity = repository.getByID(entityType, id);
		D resultDto = mapper.map(resultEntity, resultType);
		return resultDto;
	}
```

FlowItem:
```java
@JsonApiResource(type = "flow.items")
public class FlowItemDto extends EntityDto {
	@JsonApiToOne
	private AtomicExerciseDto exercise;
	@JsonApiToOne
	private FlowDto flow;
	@JsonProperty
	private Timing timing;
```

Flow:
```java
JsonApiResource(type = "flows")
public class FlowDto extends ExerciseDto {
	@JsonApiToMany
	private List<FlowItemDto> items = new ArrayList<>();
```

![tooltip_002](https://cloud.githubusercontent.com/assets/148149/14718649/2e7a6410-07f8-11e6-9ced-37b16f9914d1.png)

GET http://localhost:8080/api/flow.items/flowitem.hollow?include[flow.items]=flow

RESPONSE BODY:
```json
{
  "data": {
    "type": "flow.items",
    "id": "flowitem.hollow",
    "attributes": {
      "timing": {
        "value": 10,
        "unit": "BREATH"
      }
    },
    "relationships": {
      "exercise": {
        "links": {
          "self": "http://localhost:8080/api/flow.items/flowitem.hollow/relationships/exercise",
          "related": "http://localhost:8080/api/flow.items/flowitem.hollow/exercise"
        },
        "data": {
          "type": "atomic-exercises",
          "id": "hollow"
        }
      },
      "flow": {
        "links": {
          "self": "http://localhost:8080/api/flow.items/flowitem.hollow/relationships/flow",
          "related": "http://localhost:8080/api/flow.items/flowitem.hollow/flow"
        },
        "data": {
          "type": "flows",
          "id": "torso"
        }
      }
    },
    "links": {
      "self": "http://localhost:8080/api/flow.items/flowitem.hollow"
    }
  },
  "included": []
}
```
Using io.katharsis:katharsis-spring:2.3.1

Thanks for your time.

**Comment by meshuga** [comment]
There's still a problem with a regex in https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/queryParams/QueryParams.java#L357 
It should be `[^\\]\\[]+(?<!\[)(?=\])`.
